
#import "EntypoSymbol.h"
#import <CoreText/CoreText.h>

@interface EntypoSymbol ()

@property (strong, nonatomic) NSMutableAttributedString *symbolAttributedString;
@property (nonatomic) CGFloat fontSize;

@end

@implementation EntypoSymbol

+ (void)initialize {
    
    if (self == EntypoSymbol.class) {
        
        NSURL *url = [[NSBundle bundleForClass:self] URLForResource:@"entypo" withExtension:@"ttf"];
        
        CGDataProviderRef fontDataProvider = CGDataProviderCreateWithURL((__bridge CFURLRef)url);
        CGFontRef newFont = CGFontCreateWithDataProvider(fontDataProvider);
        CGDataProviderRelease(fontDataProvider);
        
        CFErrorRef error;
        CTFontManagerRegisterGraphicsFont(newFont, &error);
        CGFontRelease(newFont);
    }
}

+ (instancetype)iconWithCode:(NSString *)code fontSize:(CGFloat)fontSize {
    
    EntypoSymbol *symbol = [EntypoSymbol new];
    symbol.fontSize = fontSize;
    symbol.symbolAttributedString = [NSMutableAttributedString.alloc initWithString:code attributes:@{NSFontAttributeName:[self iconFontWithSize:fontSize]}];
    
    return symbol;
}

+ (UIFont *)iconFontWithSize:(CGFloat)size {
    UIFont *font = [UIFont fontWithName:@"entypo" size:size];
    return font;
}

- (UIImage *)imageWithSize:(CGSize)imageSize {
    UIGraphicsBeginImageContextWithOptions(imageSize, NO, [UIScreen.mainScreen scale]);
    
    [self.symbolAttributedString drawInRect:({
        CGSize iconSize = [self.symbolAttributedString size];
        CGFloat xOffset = (imageSize.width - iconSize.width) / 2.0;
        CGFloat yOffset = (imageSize.height - iconSize.height) / 2.0;
        CGRectMake(xOffset, yOffset, iconSize.width, iconSize.height);
    })];
    
    UIImage *iconImage = UIGraphicsGetImageFromCurrentImageContext();
    
    UIGraphicsEndImageContext();

    return iconImage;
}

- (UIImage *)image {
    return [self imageWithSize:CGSizeMake(self.fontSize, self.fontSize)];
}

- (void)addAttributes:(NSDictionary *)attributes {
    [self.symbolAttributedString addAttributes:attributes range:[self symbolAttributedStringRange]];
}

- (void)addAttribute:(NSString *)name value:(id)value {
    [self.symbolAttributedString addAttribute:name value:value range:[self symbolAttributedStringRange]];
}

- (id)attribute:(NSString *)attributeName {
    return [self.symbolAttributedString attributesAtIndex:0 effectiveRange:NULL];
}

- (NSRange)symbolAttributedStringRange {
    return NSMakeRange(0, [self.symbolAttributedString length]);
}

const struct EntypoIconCode EntypoIconCode = {
    .baidu = @"\ue749",
    .houzz = @"\ue74a",
    .windowsStore = @"\ue74b",
    .googlePlay = @"\ue74c",
    .appStore = @"\ue74d",
    .mailWithCircle = @"\ue74e",
    .medium = @"\ue74f",
    .mediumWithCircle = @"\ue750",
    .raftWithCircle = @"\ue751",
    .raft = @"\ue752",
    .qqWithCircle = @"\ue753",
    .youkoWithCircle = @"\ue754",
    .youko = @"\ue755",
    .rainbow = @"\ue756",
    .tripadvisor = @"\ue757",
    .basecamp = @"\ue758",
    .creativeCloud = @"\ue759",
    .smashing = @"\ue75a",
    .paypal = @"\ue75b",
    .behance = @"\ue75c",
    .mixi = @"\ue75d",
    .soundcloud = @"\ue75e",
    .picasa = @"\ue75f",
    .googleDrive = @"\ue760",
    .sinaWeibo = @"\ue761",
    .renren = @"\ue762",
    .swarm = @"\ue763",
    .scribd = @"\ue764",
    .foursquare = @"\ue765",
    .flattr = @"\ue766",
    .evernote = @"\ue767",
    .slideshare = @"\ue768",
    .googleHangouts = @"\ue769",
    .qq = @"\ue76a",
    .onedrive = @"\ue76b",
    .dropbox = @"\ue76c",
    .icloud = @"\ue76d",
    .grooveshark = @"\ue76e",
    .yelp = @"\ue76f",
    .skypeWithCircle = @"\ue770",
    .skype = @"\ue771",
    .pxWithCircle = @"\ue772",
    .px = @"\ue773",
    .xingWithCircle = @"\ue774",
    .xing = @"\ue775",
    .vineWithCircle = @"\ue776",
    .vine = @"\ue777",
    .vkWithCircle = @"\ue778",
    .vkAlternitive = @"\ue779",
    .vk = @"\ue77a",
    .spotifyWithCircle = @"\ue77b",
    .spotify = @"\ue77c",
    .rdioWithCircle = @"\ue77d",
    .rdio = @"\ue77e",
    .lastfm = @"\ue77f",
    .lastfmWithCircle = @"\ue780",
    .stumbleuponWithCircle = @"\ue781",
    .stumbleupon = @"\ue782",
    .dribbbleWithCircle = @"\ue783",
    .dribbble = @"\ue784",
    .linkedin = @"\ue785",
    .linkedinWithCircle = @"\ue786",
    .tumblrWithCircle = @"\ue787",
    .tumblr = @"\ue788",
    .pinterest = @"\ue789",
    .pinterestWithCircle = @"\ue78a",
    .instagramWithCircle = @"\ue78b",
    .instagram = @"\ue78c",
    .google = @"\ue79a",
    .googleWithCircle = @"\ue799",
    .facebookWithCircle = @"\ue798",
    .facebook = @"\ue797",
    .twitter = @"\ue796",
    .twitterWithCircle = @"\ue795",
    .vimeoWithCircle = @"\ue794",
    .vimeo = @"\ue793",
    .youtube = @"\ue792",
    .youtubeWithCircle = @"\ue791",
    .flickrWithCircle = @"\ue790",
    .flickr = @"\ue78f",
    .githubWithCircle = @"\ue78e",
    .github = @"\ue78d",
    .crop = @"\ue600",
    .mousePointer = @"\ue601",
    .fingerprint = @"\ue602",
    .videoCamera = @"\ue603",
    .bug = @"\ue604",
    .tabletMobileCombo = @"\ue605",
    .newsletter = @"\ue606",
    .notificationsOff = @"\ue607",
    .flower = @"\ue608",
    .eyeWithLine = @"\ue609",
    .merge = @"\ue60a",
    .creativeCommonsPublicDomain = @"\ue60b",
    .creativeCommonsRemix = @"\ue60c",
    .creativeCommonsShare = @"\ue60d",
    .creativeCommonsSharealike = @"\ue60e",
    .creativeCommonsNoncommercialEu = @"\ue60f",
    .creativeCommonsNoncommercialUs = @"\ue610",
    .creativeCommonsNoderivs = @"\ue611",
    .creativeCommonsAttribution = @"\ue612",
    .creativeCommons = @"\ue613",
    .warning = @"\ue614",
    .documentLandscape = @"\ue615",
    .classicComputer = @"\ue616",
    .removeUser = @"\ue617",
    .controllerFastBackward = @"\ue618",
    .addToList = @"\ue619",
    .dotsThreeHorizontal = @"\ue61a",
    .dotsTwoHorizontal = @"\ue61b",
    .dotSingle = @"\ue61c",
    .dotsTwoVertical = @"\ue61d",
    .dotsThreeVertical = @"\ue61e",
    .selectArrows = @"\ue61f",
    .arrowLongRight = @"\ue620",
    .arrowLongUp = @"\ue621",
    .arrowLongDown = @"\ue622",
    .arrowLongLeft = @"\ue623",
    .chevronWithCircleRight = @"\ue624",
    .chevronWithCircleUp = @"\ue625",
    .chevronWithCircleDown = @"\ue626",
    .chevronWithCircleLeft = @"\ue627",
    .chevronThinRight = @"\ue628",
    .chevronThinUp = @"\ue629",
    .chevronThinDown = @"\ue62a",
    .chevronThinLeft = @"\ue62b",
    .chevronSmallRight = @"\ue62c",
    .chevronSmallUp = @"\ue62d",
    .chevronSmallDown = @"\ue62e",
    .chevronSmallLeft = @"\ue62f",
    .chevronRight = @"\ue630",
    .chevronUp = @"\ue631",
    .chevronDown = @"\ue632",
    .chevronLeft = @"\ue633",
    .triangleRight = @"\ue634",
    .triangleUp = @"\ue635",
    .triangleDown = @"\ue636",
    .triangleLeft = @"\ue637",
    .arrowWithCircleRight = @"\ue638",
    .arrowWithCircleUp = @"\ue639",
    .arrowWithCircleDown = @"\ue63a",
    .arrowWithCircleLeft = @"\ue63b",
    .arrowRight = @"\ue63c",
    .arrowUp = @"\ue63d",
    .arrowDown = @"\ue63e",
    .arrowLeft = @"\ue63f",
    .arrowBoldRight = @"\ue640",
    .arrowBoldUp = @"\ue641",
    .arrowBoldDown = @"\ue642",
    .arrowBoldLeft = @"\ue643",
    .flowParallel = @"\ue644",
    .flowLine = @"\ue645",
    .flowTree = @"\ue646",
    .flowBranch = @"\ue647",
    .flowCascade = @"\ue648",
    .soundMute = @"\ue649",
    .sound = @"\ue64a",
    .controllerVolume = @"\ue64b",
    .resize100 = @"\ue64c",
    .resizeFullScreen = @"\ue64d",
    .controllerNext = @"\ue64e",
    .controllerJumpToStart = @"\ue64f",
    .controllerFastForward = @"\ue650",
    .controllerStop = @"\ue651",
    .controllerRecord = @"\ue652",
    .controllerPaus = @"\ue653",
    .controllerPlay = @"\ue654",
    .openBook = @"\ue655",
    .bookmarks = @"\ue656",
    .bookmark = @"\ue657",
    .layers = @"\ue658",
    .uploadToCloud = @"\ue659",
    .cloud = @"\ue65a",
    .uninstall = @"\ue65b",
    .install = @"\ue65c",
    .save = @"\ue65d",
    .download = @"\ue65e",
    .upload = @"\ue65f",
    .trash = @"\ue660",
    .emojiFlirt = @"\ue661",
    .archive = @"\ue662",
    .timeSlot = @"\ue663",
    .mask = @"\ue664",
    .sportsClub = @"\ue665",
    .folderVideo = @"\ue666",
    .folderMusic = @"\ue667",
    .folderImages = @"\ue668",
    .folder = @"\ue669",
    .music = @"\ue66a",
    .video = @"\ue66b",
    .images = @"\ue66c",
    .imageInverted = @"\ue66d",
    .image = @"\ue66e",
    .copy = @"\ue66f",
    .spreadsheet = @"\ue670",
    .textDocumentInverted = @"\ue671",
    .textDocument = @"\ue672",
    .documents = @"\ue673",
    .document = @"\ue674",
    .menu = @"\ue675",
    .grid = @"\ue676",
    .list = @"\ue677",
    .text = @"\ue678",
    .unread = @"\ue679",
    .emojiSad = @"\ue67a",
    .emojiNeutral = @"\ue67b",
    .emojiHappy = @"\ue67c",
    .untag = @"\ue67d",
    .tag = @"\ue67e",
    .alignVerticalMiddle = @"\ue67f",
    .alignHorizontalMiddle = @"\ue680",
    .alignRight = @"\ue681",
    .alignTop = @"\ue682",
    .alignBottom = @"\ue683",
    .alignLeft = @"\ue684",
    .backInTime = @"\ue685",
    .swap = @"\ue686",
    .retweet = @"\ue687",
    .loop = @"\ue688",
    .levelUp = @"\ue689",
    .levelDown = @"\ue68a",
    .back = @"\ue68b",
    .shuffle = @"\ue68c",
    .circle = @"\ue68d",
    .cw = @"\ue68e",
    .ccw = @"\ue68f",
    .cycle = @"\ue690",
    .infoWithCircle = @"\ue691",
    .helpWithCircle = @"\ue692",
    .help = @"\ue693",
    .info = @"\ue694",
    .block = @"\ue695",
    .erase = @"\ue696",
    .plus = @"\ue697",
    .minus = @"\ue698",
    .circleWithCross = @"\ue699",
    .circleWithPlus = @"\ue69a",
    .circleWithMinus = @"\ue69b",
    .squaredCross = @"\ue69c",
    .squaredPlus = @"\ue69d",
    .squaredMinus = @"\ue69e",
    .cross = @"\ue69f",
    .check = @"\ue6a0",
    .switchIcon = @"\ue6a1",
    .logOut = @"\ue6a2",
    .login = @"\ue6a3",
    .lockOpen = @"\ue6a4",
    .lock = @"\ue6a5",
    .circularGraph = @"\ue6a6",
    .areaGraph = @"\ue6a7",
    .barGraph = @"\ue6a8",
    .pieChart = @"\ue6a9",
    .lineGraph = @"\ue6aa",
    .sweden = @"\ue6ab",
    .water = @"\ue6ac",
    .thermometer = @"\ue6ad",
    .signal = @"\ue6ae",
    .rss = @"\ue6af",
    .ticket = @"\ue6b0",
    .box = @"\ue6b1",
    .database = @"\ue6b2",
    .clipboard = @"\ue6b3",
    .voicemail = @"\ue6b4",
    .dialPad = @"\ue6b5",
    .wallet = @"\ue6b6",
    .shoppingBasket = @"\ue6b7",
    .shoppingBag = @"\ue6b8",
    .shoppingCart = @"\ue6b9",
    .shop = @"\ue6ba",
    .creditCard = @"\ue6bb",
    .lightBulb = @"\ue6bc",
    .infinity = @"\ue6bd",
    .tv = @"\ue6be",
    .code = @"\ue6bf",
    .soundMix = @"\ue6c0",
    .adjust = @"\ue6c1",
    .lightUp = @"\ue6c2",
    .lightDown = @"\ue6c3",
    .progressEmpty = @"\ue6c4",
    .progressOne = @"\ue6c5",
    .progressTwo = @"\ue6c6",
    .progressFull = @"\ue6c7",
    .publish = @"\ue6c8",
    .browser = @"\ue6c9",
    .scissors = @"\ue6ca",
    .eraser = @"\ue6cb",
    .pencil = @"\ue6cc",
    .flatBrush = @"\ue6cd",
    .roundBrush = @"\ue6ce",
    .keyboard = @"\ue6cf",
    .radio = @"\ue6d0",
    .globe = @"\ue6d1",
    .trafficCone = @"\ue6d2",
    .suitcase = @"\ue6d3",
    .brush = @"\ue6d4",
    .ruler = @"\ue6d5",
    .labFlask = @"\ue6d6",
    .rocket = @"\ue6d7",
    .cup = @"\ue6d8",
    .gameController = @"\ue6d9",
    .drive = @"\ue6da",
    .cake = @"\ue6db",
    .magnet = @"\ue6dc",
    .funnel = @"\ue6dd",
    .bucket = @"\ue6de",
    .battery = @"\ue6df",
    .stopwatch = @"\ue6e0",
    .key = @"\ue6e1",
    .network = @"\ue6e2",
    .language = @"\ue6e3",
    .colours = @"\ue6e4",
    .gauge = @"\ue6e5",
    .tree = @"\ue6e6",
    .hourGlass = @"\ue6e7",
    .air = @"\ue6e8",
    .briefcase = @"\ue6e9",
    .bowl = @"\ue6ea",
    .vinyl = @"\ue6eb",
    .drop = @"\ue6ec",
    .thunderCloud = @"\ue6ed",
    .calendar = @"\ue6ee",
    .flash = @"\ue6ef",
    .mic = @"\ue6f0",
    .clock = @"\ue6f1",
    .hand = @"\ue6f2",
    .credit = @"\ue6f3",
    .eye = @"\ue6f4",
    .lifebuoy = @"\ue6f5",
    .aircraftLanding = @"\ue6f6",
    .aircraftTakeOff = @"\ue6f7",
    .shield = @"\ue6f8",
    .aircraft = @"\ue6f9",
    .news = @"\ue6fa",
    .pin = @"\ue6fb",
    .book = @"\ue6fc",
    .blackboard = @"\ue6fd",
    .graduationCap = @"\ue6fe",
    .new = @"\ue6ff",
    .medal = @"\ue700",
    .priceRibbon = @"\ue701",
    .clapperboard = @"\ue702",
    .modernMic = @"\ue703",
    .beamedNote = @"\ue704",
    .note = @"\ue705",
    .drink = @"\ue706",
    .man = @"\ue707",
    .leaf = @"\ue708",
    .palette = @"\ue709",
    .moon = @"\ue70a",
    .awarenessRibbon = @"\ue70b",
    .megaphone = @"\ue70c",
    .camera = @"\ue70d",
    .priceTag = @"\ue70e",
    .powerPlug = @"\ue70f",
    .trophy = @"\ue710",
    .tools = @"\ue711",
    .cog = @"\ue712",
    .flag = @"\ue713",
    .link = @"\ue714",
    .bell = @"\ue715",
    .print = @"\ue716",
    .calculator = @"\ue717",
    .flashlight = @"\ue718",
    .magnifyingGlass = @"\ue719",
    .popup = @"\ue71a",
    .home = @"\ue71b",
    .quote = @"\ue71c",
    .typing = @"\ue71d",
    .message = @"\ue71e",
    .address = @"\ue71f",
    .attachment = @"\ue720",
    .chat = @"\ue721",
    .compass = @"\ue722",
    .direction = @"\ue723",
    .edit = @"\ue724",
    .email = @"\ue725",
    .export = @"\ue726",
    .feather = @"\ue727",
    .forward = @"\ue728",
    .hairCross = @"\ue729",
    .heartOutlined = @"\ue72a",
    .heart = @"\ue72b",
    .inbox = @"\ue72c",
    .landline = @"\ue72d",
    .laptop = @"\ue72e",
    .locationPin = @"\ue72f",
    .location = @"\ue730",
    .mail = @"\ue731",
    .map = @"\ue732",
    .mobile = @"\ue733",
    .mouse = @"\ue734",
    .newMessage = @"\ue735",
    .notification = @"\ue736",
    .oldMobile = @"\ue737",
    .oldPhone = @"\ue738",
    .paperPlane = @"\ue739",
    .phone = @"\ue73a",
    .replyAll = @"\ue73b",
    .reply = @"\ue73c",
    .shareAlternative = @"\ue73d",
    .share = @"\ue73e",
    .shareable = @"\ue73f",
    .starOutlined = @"\ue740",
    .star = @"\ue741",
    .tablet = @"\ue742",
    .thumbsDown = @"\ue743",
    .thumbsUp = @"\ue744",
    .user = @"\ue745",
    .users = @"\ue746",
    .vCard = @"\ue747",
    .addUser = @"\ue748"
};

@end
